### PR TITLE
rewrite in ntex

### PR DESCRIPTION
**Pull request by TrashCan69420**

### CODE REVIEW

**Comment by Tricked-dev** [comment]
axum is bloated

**Comment by Tricked-dev** [comment]
rewrite to actix and maybe but axum smh

**Comment by TrashCan69420** [comment]
> rewrite to actix and maybe but axum smh

Actix cringe I'll just use ntex if I would go through all that

**Comment by Tricked-dev** [comment]
Your only making it slower by using Axum smh

**Comment by TrashCan69420** [comment]
> Your only making it slower by using Axum smh

Rewriting in dragon or whatever that one c++ framework at the top of techempowers benchmark is

**Comment by Tricked-dev** [comment]
useful commit messages thanks trashcan

**Comment by TrashCan69420** [comment]
> useful commit messages thanks trashcan

Your welcome

**Pull request closed without merging**
